"""initial tables

Revision ID: c4b9a71a058a
Revises: 
Create Date: 2020-01-05 18:49:34.510273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b9a71a058a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roulette_message',
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('channel')
    )
    op.create_table('slack_access_token',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_access_token')
    op.drop_table('roulette_message')
    # ### end Alembic commands ###
